[package]
name = "classic-mac-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
panic-abort = "0.3.2"

[profile.release]
#debug = true
codegen-units = 1
